# Generated by Django 5.0.6 on 2024-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0004_alter_musician_last_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="musician",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="bands_music_last_na_979e82_idx",
            ),
        ),
    ]
